### PR TITLE
User cant book his own gear

### PR DESCRIPTION
**Pull request by dimitrisreth**
i have created 2 users on my local database 
one user cannot edit or delete other users bike 
user cannot book his own bikes

added this in index and show views for edit delete and bookings 
"if user_signed_in? && gear.owned_by?(current_user) "

added this def in gear.rb
  def owned_by?(user)
    self.user == user
  end
  
  
Screenshot 2024-06-07 at 14 19 17
Screenshot 2024-06-07 at 14 19 27

### CODE REVIEW

**Comment by dimitrisreth** [comment]
on the first photo edit and delete are not available because its not his gear
on the second photo booking is not available because it is his gear

**Review by yaroslavgubich — COMMENTED** [review]
Looks good to me, but can you please also guide user to a page with HIS bikes ? After creating a new bike site guides me to ALL BIKES page, I need to see what I am selling. I guess we need to add another page with USER bikes, like a dashboard.

**Comment by dimitrisreth** [comment]
calendar should be ok now

like you can put minus values in a price field is ok
and we must be able to click on the calendar  anywhere not only on a tiny calendar symbol is ok
and also today's date must be pre selected automatically is ok

**Review by yaroslavgubich — CHANGES_REQUESTED** [review]
Still can use - value for a price, still can't click anywhere on calendar to open it, start date is not preselected. 
image
image

**Pull request closed without merging**
